language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t urosorozel/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true urosorozel/docker-react npm run test
